type: "od"

data:
  train: "F:/source/repos/Daten/ObjectDetection/Her2512/train"
  valid: "F:/source/repos/Daten/ObjectDetection/Her2512/valid"
  save_folder: "runs"
  weights: "yolov5s.pt"
# anchors
settings:
  nc: 1
  epochs: 300
  imgsize: 512
  batch_size: 4



  

