type: "od"

data:
  train: "C:/Users/phili/Downloads/Telegram Desktop/ODTest/dataset/train"
  valid: "C:/Users/phili/Downloads/Telegram Desktop/ODTest/dataset/valid"
  #train: "C:/Users/phili/Downloads/Telegram Desktop/ViktorOD/dataset/train"
  #valid: "C:/Users/phili/Downloads/Telegram Desktop/ViktorOD/dataset/valid"
  save_folder: "runs"
  weights: "yolov5s.pt"
# anchors
settings:
  nc: 1
  epochs: 5000
  imgsize: 512
  batch_size: 1
  modelsize: "s"



  

