type: "od"

data:
  train: "F:/source/repos/Daten/ObjectDetection/SingleClassHer2256/train"
  valid: "F:/source/repos/Daten/ObjectDetection/SingleClassHer2256/valid"
  save_folder: "runs"
# anchors
settings:
  nc: 1
  epochs: 150
  imgsize: 256
  batch_size: 4

  

