type: "od"

data:
  # train: "C:/Users/phili/Downloads/Telegram Desktop/ODTest/dataset/train"
  # valid: "C:/Users/phili/Downloads/Telegram Desktop/ODTest/dataset/valid"
  # #train: "C:/Users/phili/Downloads/Telegram Desktop/ViktorOD/dataset/train"
  # #valid: "C:/Users/phili/Downloads/Telegram Desktop/ViktorOD/dataset/valid"
  # train: "C:/Users/phili/Downloads/Telegram Desktop/Nuclei_od/Nuclei_od/train"
  # valid: "C:/Users/phili/Downloads/Telegram Desktop/Nuclei_od/Nuclei_od/valid"
  # train: "F:/source/repos/VisualDL/custom_experiments/FinalHer2/train"
  # valid: "F:/source/repos/VisualDL/custom_experiments/FinalHer2/valid"
  train: "D:/Hsa/temp/projects/3834fba0-dfef-4de8-8f54-7c7078468ae8/dataset/train"
  valid: "D:/Hsa/temp/projects/3834fba0-dfef-4de8-8f54-7c7078468ae8/dataset/valid"
  #train: "C:/Users/phili/Downloads/Telegram Desktop/od_test/od_test/train"
  #valid: "C:/Users/phili/Downloads/Telegram Desktop/od_test/od_test/valid"
  save_folder: "runs"
  weights: "F:/source/repos/VisualDL/runs/exp150/weights/best.pt"
  mask_input: False
# anchors
settings:
  nc: 4
  epochs: 1500
  imgsize: 512
  batch_size: 2
  modelsize: "s" #s,m,l
  custom_data: {'structure_indices': [16, 17, 18, 19], 'image_size': 512, 'modeltype': 'object detection', 'object_based': False, 'physical_tile_size': (113.19408504630164, 113.19408504630164), 'project_type': 'dummy', 'pyramid_level': -1, 'datetime': '01/12/2021 18:09', 'structures': 'Tumor Cells 0+, Tumor Cells 1+, Tumor Cells 2+, Tumor Cells 3+', 'objects_count': 31002, 'model': 'maskrcnn', 'files': {'File': ['05_.czi', '05_.czi', '05_.czi', '05_.czi'], 'Scene': [2, 2, 2, 2]}}



  

