type: "segmentation"

data:
  train: "E:/source/repos/VisualDL/tests/segmentation/train"
  valid: "E:/source/repos/VisualDL/tests/segmentation/train"
  test: "E:/source/repos/VisualDL/tests/segmentation/train"

# anchors
models:
  - backbone: "timm-skresnext50_32x4d"
    decoder: "Unet"
  - backbone: "resnet50"
    decoder: "Unet"
  - backbone: "timm-skresnext50_32x4d"
    decoder: "DeepLabV3Plus"

settings:
  nc: 2
  in_channels: 3
  epochs: 1
  optimizer: "AdamW"
  lr: 0.0001
  workers: 0
  batch_size:
    - 4
    - 4
    - 4
  gradient_accumulation: 32
  criterions: #criterions defined in segmentation_models_pytorch.utils.losses can be used
    - "CrossEntropyLoss"
  lr: 0.0001
  tensorboard_log_dir: "tensorboard_logs"
  metrics:
    - name: "Accuracy"
      params: "num_classes=2"
  monitor_metric: 
    name: "Accuracy"
    params: "num_classes=2"

transforms:
  width: 256
  height: 256
  h_flip: 0.5
  v_flip: 0.5
  brightness: 0.2
  contrast: 0.2
  rgb_shift : 0.2
  random_shadow: 0.2
  blur: 0.2


  

