type: "segmentation"

data:
  train: "C:/Users/phili/Downloads/Telegram Desktop/Cells/train"
  valid: "C:/Users/phili/Downloads/Telegram Desktop/Cells/valid"
  test: "C:/Users/phili/Downloads/Telegram Desktop/Cells/valid"

# anchors
models:


  - backbone: "efficientnet-b7"
    decoder: "UnetPlusPlus"

settings:
  nc: 2
  in_channels: 3
  epochs: 5000
  optimizer: "AdamW"
  lr: 0.0001
  workers: 0
  batch_size:
    - 8

  gradient_accumulation: 8
  criterions: #criterions defined in segmentation_models_pytorch.utils.losses can be used
    - "CrossEntropyLoss"
  tensorboard_log_dir: "tensorboard_logs"
  metrics:
    - name: "Accuracy"
      params: "num_classes=2"
    - name: "IoU"
      params: "num_classes=2"

transforms:
  width: 128
  height: 128
  h_flip: 0.5
  v_flip: 0.5
  brightness: 0.0
  contrast: 0.0
  rgb_shift : 0.0
  random_shadow: 0.0
  blur: 0.0


  

