weights: yolov5s.pt
cfg: F:\source\repos\VisualDL\visualdl\trainer\detection\../../dependencies/yolov5/models/yolov5m.yaml
data: F:\source\repos\VisualDL\visualdl\trainer\detection\../../dependencies/yolov5/data/hsa.yaml
hyp: F:\source\repos\VisualDL\visualdl\trainer\detection\../../dependencies/yolov5/data/hyps/hyp.scratch.yaml
epochs: 150
batch_size: 16
imgsz: 256
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: 0
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 0
project: runs/train
entity: null
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
local_rank: -1
freeze: 0
patience: 100
batch-size: 4
batch: 4
save_dir: runs\train\exp
