type: "segmentation"

data:
  #train: "C:/Users/phili/Downloads/Telegram Desktop/NeueCells/Cells/train"
  #valid: "C:/Users/phili/Downloads/Telegram Desktop/NeueCells/Cells/valid"
  #test: "C:/Users/phili/Downloads/Telegram Desktop/NeueCells/Cells/valid"
  #train: "E:/source/repos/Daten/HER-N/hubt/dataset/Cells/train"
  #valid: "E:/source/repos/Daten/HER-N/hubt/dataset/Cells/valid"
  #test: "E:/source/repos/Daten/HER-N/hubt/dataset/Cells/valid"
  #train: "E:/source/repos/Daten/PLA/train"
  #valid: "E:/source/repos/Daten/PLA/val"
  #test: "E:/source/repos/Daten/PLA/val"
  train: "E:/source/repos/Daten/Nuclei/Nuclei/Nuclei/train"
  valid: "E:/source/repos/Daten/Nuclei/Nuclei/Nuclei/val"
  test: "E:/source/repos/Daten/Nuclei/Nuclei/Nuclei/val"
  #train: "custom_experiments/train"
  #valid: "custom_experiments/valid"
  #test: "custom_experiments/valid"
  

  weights: ["None", "None"]

  save_folder: "E:/source/repos/VisualDL" 

# anchors
models:

  - backbone: "tu-resnest50d"
    decoder: "Unet"

  - backbone: "tu-resnest50d"
    decoder: "resunet"

settings:
  nc: 6
  in_channels: 3
  epochs: 500
  optimizer: "AdamW"
  lr: 0.0001
  workers: 0
  batch_size: [8,8]
  max_image_size: 256 #must be set for transformer based models because of the positional embedding
  scales: "None" #or None
  use_attention: True
  gradient_accumulation: 8
  criterions: #criterions defined in segmentation_models_pytorch.utils.losses can be used
    - "CrossEntropyLoss"

  tensorboard_log_dir: "tensorboard_log"
  metrics:
    - name: "Accuracy"
      params: "num_classes=6"
    - name: "IoU"
      params: "num_classes=6"
  monitor_metric_name: "IoU"
  monitor_metric_params: "num_classes=6"
  class_weights: False
  calculate_weight_map: False
  early_stopping: 15

transforms:
  Resize: width = 128, height = 128
  HorizontalFlip: p=0.25
  VerticalFlip: p=0.25
  RandomBrightnessContrast: p=0.0
  RGBShift: p=0.0
  RandomShadow : p=0.0
  GaussianBlur: p=0.0
  Transpose: p=0.15
  RandomRotate90: p=0.15
  Perspective: p=0.0
  Affine: p=0.0
  ToGray: p=0.0
  RandomScale: p=0.0


  

