type: "segmentation"

data:
  #train: "C:/Users/phili/Downloads/Telegram Desktop/CellsFinal/Cells/right side/cells/train"
  #valid: "C:/Users/phili/Downloads/Telegram Desktop/CellsFinal/Cells/right side/cells/valid"
  #test: "C:/Users/phili/Downloads/Telegram Desktop/CellsFinal/Cells/right side/cells/valid"
  train: "C:/Users/phili/Downloads/Telegram Desktop/hubt/dataset/Cells/train"
  valid: "C:/Users/phili/Downloads/Telegram Desktop/hubt/dataset/Cells/valid"
  test: "C:/Users/phili/Downloads/Telegram Desktop/hubt/dataset/Cells/valid"
  

  weights: 
    - "E:/source/repos/VisualDL/PLA2/timm-u-resnest50d, UnetPlusPlus.pt"

  save_folder: "E:/source/repos/VisualDL" 

# anchors
models:
  - backbone: "timm-u-resnest50d"
    decoder: "UnetPlusPlus"


settings:
  nc: 2
  in_channels: 3
  epochs: 5000
  optimizer: "AdamW"
  lr: 0.0001
  workers: 0
  batch_size:
    - 8

  gradient_accumulation: 8
  criterions: #criterions defined in segmentation_models_pytorch.utils.losses can be used
    - "CrossEntropyLoss"
  tensorboard_log_dir: "tensorboard_log"
  metrics:
    - name: "Accuracy"
      params: "num_classes=2"
    - name: "IoU"
      params: "num_classes=2"
  monitor_metric_name: "IoU"
  monitor_metric_params: "num_classes=2"
  class_weights: False
  calculate_weight_map: True

transforms:
  Resize: width = 256, height = 256
  HorizontalFlip: p=0.25
  VerticalFlip: p=0.25
  RandomBrightnessContrast: p=0.15
  RGBShift: p=0.0
  RandomShadow : p=0.0
  GaussianBlur: p=0.0
  Transpose: p=0.15
  RandomRotate90: p=0.15
  Perspective: p=0.0
  Affine: p=0.0
  ToGray: p=0.0
  RandomScale: p=0.0


  

