type: "segmentation"

data:
  #train: "C:/Users/phili/Downloads/Telegram Desktop/Cells/train"
  #valid: "C:/Users/phili/Downloads/Telegram Desktop/Cells/valid"
  #test: "C:/Users/phili/Downloads/Telegram Desktop/Cells/valid"
  train: "E:/source/repos/HSAData/Evican/train"
  valid: "E:/source/repos/HSAData/Evican/valid"
  test: "E:/source/repos/HSAData/Evican/valid"

  weights: 
    - "imagenet"
    - "imagenet"
    - "imagenet"

  save_folder: "" 

# anchors
models:
  #- backbone: "timm-regnety_064"
  #  decoder: "EfficientUnetPlusPlus"


  - backbone: "timm-regnety_064"
    decoder: "UnetPlusPlus"



settings:
  nc: 2
  in_channels: 3
  epochs: 5000
  optimizer: "AdamW"
  lr: 0.0001
  workers: 0
  batch_size:
    - 8
   # - 4

  gradient_accumulation: 8
  criterions: #criterions defined in segmentation_models_pytorch.utils.losses can be used
    - "CrossEntropyLoss"
  tensorboard_log_dir: "tensorboard_logs"
  metrics:
    - name: "Accuracy"
      params: "num_classes=2"
    - name: "IoU"
      params: "num_classes=2"
  monitor_metric_name: "IoU"
  monitor_metric_params: "num_classes=2"
  class_weights: True
transforms:
  width: 256
  height: 256
  h_flip: 0.5
  v_flip: 0.5
  brightness: 0.0
  contrast: 0.0
  rgb_shift : 0.0
  random_shadow: 0.0
  blur: 0.0


  

