type: "classification"

data:
  train: "C:/Users/phili/Downloads/Telegram Desktop/dataset"
  valid: "C:/Users/phili/Downloads/Telegram Desktop/dataset_valid"
  test: "C:/Users/phili/Downloads/Telegram Desktop/dataset_valid"

  weights: 
    - None

  save_folder: "E:/source/repos/VisualDL" 
  
# anchors
model_names:
  - "resnext50_32x4d"


settings:
  nc: 5
  epochs: 100
  optimizer: "AdamW"
  lr: 0.0001
  workers: 0
  batch_size:
    - 8
  gradient_accumulation: 8
  criterions:
    - "CrossEntropyLoss"
  tensorboard_log_dir: "tensorboard_logs"
  metrics:
    - name: "F1"
      params: "num_classes=5"
    - name: "Accuracy"
      params: ""
    - name: "CohenKappa"
      params: "num_classes=5"

  monitor_metric_name: "Accuracy"
  monitor_metric_params: "num_classes=5"
  class_weights: False
  calculate_weight_map: False
  early_stopping: 50
  
transforms:
  Resize: width = 512, height = 512
  HorizontalFlip: p=0.25
  VerticalFlip: p=0.25
  RandomBrightnessContrast: p=0
  RGBShift: p=0.0
  RandomShadow : p=0.0
  GaussianBlur: p=0.0
  Transpose: p=0
  RandomRotate90: p=0.15
  Perspective: p=0.0
  Affine: p=0.0
  ToGray: p=0.0
  RandomScale: p=0.0


  

