type: "series"

data:
  train: "F:/source/repos/Evonik/Evonik/Spektren/Gemische/csv Dateien/rnngemischetrain.json" #path to json
  valid: "F:/source/repos/Evonik/Evonik/Spektren/Gemische/csv Dateien/rnngemischetest.json" #path to json
  weights: ["model.pt"]
  save_folder: "" 

settings:
  outputs: {
    "classes" : 0, #einzelsubstanz -> für gemische 0 hier
    "continuous": 3 # einzelsubstanz -> für gemische 3 hier
  }
  multiple_classes_per_datapoint: False
  in_channels: 3
  epochs: 3000
  optimizer: "AdamW"
  lr: 1e-4
  workers: 0
  batch_size: 4
  use_lstm: False
  
  modelsize: s
  metrics:
    - name: "Accuracy"
      params: ""

  tensorboard_log_dir: "tensorboard_log"
  custom_data: {'structure_indices': [2],
  'image_size': 1024,
  'modeltype': 'segmentation',
  'object_based': False,
  'physical_tile_size': (226.388852600035, 226.388852600035),
  'project_type': 'dummy',
  'pyramid_level': 0,
  'datetime': '21/01/2022 15:33',
  'structures': 'Glomerulus',
  'objects_count': 312,
  'model': "[{'backbone': 'tu-resnest26d', 'decoder': 'Unet'}]",
  'files': {'File': ['05_.czi'],
  'Scene': [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]},
  'calculate_weight_map': False}


  

