type: "instance"

data:
  train: "C:/Users/phili/Downloads/Telegram Desktop/AbsolutFinal/dataset/train"
  valid: "C:/Users/phili/Downloads/Telegram Desktop/AbsolutFinal/dataset/valid"
  train: "C:/Users/phili/Downloads/Telegram Desktop/Erlangen/dataset/train"
  valid: "C:/Users/phili/Downloads/Telegram Desktop/Erlangen/dataset/valid"
  train: "F:/source/repos/Daten/Glomeruli/trainer"
  valid: "F:/source/repos/Daten/Glomeruli/valid"
  train: "C:/Users/phili/Downloads/Telegram Desktop/MarieUke/train"
  valid: "C:/Users/phili/Downloads/Telegram Desktop/MarieUke/valid"
  #train: "D:/Hsa/temp/projects/3834fba0-dfef-4de8-8f54-7c7078468ae8/dataset/train"
  #valid: "D:/Hsa/temp/projects/3834fba0-dfef-4de8-8f54-7c7078468ae8/dataset/valid"
  save_folder: ""
  weights: "asd.ptt"
# anchors
settings:
  epochs: 10
  batch_size: 1
  image_size: 512
  max_boxes_per_image: 800
  nc: 5
  anchors: [32,64,128,256,512]
  calculate_class_weights: False
  custom_data: {'structure_indices': [16, 17, 18, 19], 'image_size': 512, 'modeltype': 'instance segmentation', 'object_based': False, 'physical_tile_size': (113.19408504630164, 113.19408504630164), 'project_type': 'dummy', 'pyramid_level': -1, 'datetime': '01/12/2021 18:09', 'structures': 'Tumor Cells 0+, Tumor Cells 1+, Tumor Cells 2+, Tumor Cells 3+', 'objects_count': 31002, 'model': 'maskrcnn', 'files': {'File': ['05_.czi', '05_.czi', '05_.czi', '05_.czi'], 'Scene': [2, 2, 2, 2]}} #whaever ya want

transforms:
  Resize: width = 512, height = 512
  HorizontalFlip: p=0.25
  VerticalFlip: p=0.25
  RandomBrightnessContrast: p=0.0
  RGBShift: p=0.0
  RandomShadow : p=0.00
  GaussianBlur: p=0.1
  Transpose: p=0.0
  RandomRotate90: p=0.15
  Perspective: p=0.00
  Affine: p=0.00
  ToGray: p=0.0
  RandomScale: p=0.0



  

