type: "classification"

data:
  train: "E:/source/repos/VisualDL/tests/classification"
  valid: ""
  test: ""

settings:
  nc: 2
  epochs: 10
  optimizer: "Adam"
  lr: 0.0001
  workers: 0
  batch_size:
    - 1
  criterions:
    - 'CrossEntropyLoss'

transform:
  bub: 3
# anchors
model_names:
  - "resnet26"

