type: "classification"

data:
  train: "E:/downloads/archive/train"
  valid: "E:/downloads/archive/test"
  test: "E:/downloads/archive/test"

# anchors
model_names:
  - "efficientnet_b0"
  - "resnet50"
  - "efficientnet_b3"

settings:
  nc: 2
  epochs: 3
  optimizer: "Adam"
  lr: 0.0001
  workers: 0
  batch_size:
    - 32
    - 32
    - 32
  criterions:
    - "CrossEntropyLoss"

  tensorboard_log_dir: "tensorboard_logs"


  metrics:
    - name: "F1"
      params: "num_classes=2"
    - name: "Accuracy"
      params: ""
    - name: "CohenKappa"
      params: "num_classes=2"

  monitor_metric: 
    name: "Accuracy"
    params: "num_classes=2"

transforms:
  width: 256
  height: 256
  h_flip: 0.5
  v_flip: 0.5
  brightness: 0.2
  contrast: 0.2
  rgb_shift : 0.2
  random_shadow: 0.2
  blur: 0.2


  

