type: "classification"

data:
  train: "E:/downloads/archive/train"
  valid: "E:/downloads/archive/test"
  test: "E:/downloads/archive/test"

# anchors
model_names:
  - "resnet50"
  - "resnest50d"
  - "resnet26"
settings:
  nc: 2
  epochs: 100
  optimizer: "Adam"
  lr: 0.0001
  workers: 0
  batch_size:
    - 32
    - 32
    - 32
  gradient_accumulation: 64
  criterions:
    - "CrossEntropyLoss"
  tensorboard_log_dir: "tensorboard_logs"
  metrics:
    - name: "F1"
      params: "num_classes=2"
    - name: "Accuracy"
      params: ""
    - name: "CohenKappa"
      params: "num_classes=2"

transforms:
  width: 256
  height: 256
  h_flip: 0.5
  v_flip: 0.5
  brightness: 0.0
  contrast: 0.0
  rgb_shift : 0.0
  random_shadow: 0.0
  blur: 0.0


  

