type: "classification"

data:
  train: "E:/source/repos/VisualDL/tests/classification"
  valid: ""
  test: ""

settings:
  nc: 2
  epochs: 1
  optimizer: "Adam"
  lr: 0.0001
  workers: 0
  batch_size:
    - 1
    - 1
  criterions:
    - "CrossEntropyLoss"


  metrics:
    - name: "F1"
      params: "num_classes=2"
    - name: "Accuracy"
      params: ""
    - name: "CohenKappa"
      params: "num_classes=2"
    
    
        
    
transform:
  bub: 3
# anchors
model_names:
  - "resnet26"
  - "resnet50"

