type: "classification"

data:
  train: "E:/downloads/archive/train"
  valid: "E:/downloads/archive/test"
  test: "E:/downloads/archive/test"

settings:
  nc: 2
  epochs: 6
  optimizer: "Adam"
  lr: 0.0001
  workers: 0
  batch_size:
    - 32
    - 32
    - 32
  criterions:
    - "CrossEntropyLoss"

  tensorboard_log_dir: "tensorboard_logs"


  metrics:
    - name: "F1"
      params: "num_classes=2"
    - name: "Accuracy"
      params: ""
    - name: "CohenKappa"
      params: "num_classes=2"

  monitor_metric: 
    name: "Accuracy"
    params: "num_classes=2"

        
    
transform:
  bub: 3
# anchors
model_names:
  - "efficientnet_b0"
  - "resnet50"
  - "efficientnet_b3"
  

